services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PORT=8080
  #     - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
  #     - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
  #     - STRAVA_REDIRECT_URI=${STRAVA_REDIRECT_URI}
  #     - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
  #     - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
  #     - INFLUXDB_ORG=${INFLUXDB_ORG}
  #     - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
  #     - TOKEN_REFRESH_INTERVAL=${TOKEN_REFRESH_INTERVAL:-24h}
  #     - DATA_IMPORT_INTERVAL=${DATA_IMPORT_INTERVAL:-1h}
  #     - TWITTER_API_KEY=${TWITTER_API_KEY}
  #     - TWITTER_API_SECRET=${TWITTER_API_SECRET}
  #     - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
  #     - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #   depends_on:
  #     - influxdb
  #   volumes:
  #     - ../conf:/app/conf:ro
  #   restart: unless-stopped
  #   networks:
  #     - strava-net

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-strava}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-activities}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-your-super-secret-auth-token}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped
    networks:
      - strava-net

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - strava-net

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:

networks:
  strava-net:
    driver: bridge
